# Generated by Django 5.1.6 on 2025-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('radius', models.DecimalField(decimal_places=4, max_digits=10)),
                ('texture', models.DecimalField(decimal_places=4, max_digits=10)),
                ('smoothness', models.DecimalField(decimal_places=4, max_digits=10)),
                ('area', models.DecimalField(decimal_places=4, max_digits=10)),
                ('compactness', models.DecimalField(decimal_places=4, max_digits=10)),
                ('concavity', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('mammogram_image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
