# Generated by Django 5.1.6 on 2025-06-21 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_personaldetails_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
