# Generated by Django 5.1.6 on 2025-06-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_imageupload_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='uploaded_at',
        ),
    ]
